### PR TITLE
Update deps, and correct a bug preventing build

### PR DESCRIPTION
**Pull request by ricecake**

### CODE REVIEW

**Comment by tsloughter** [comment]
This only works for erlang 18 though, right?

**Comment by tsloughter** [comment]
We should keep support for at least 17. So I guess we need a `rebar.config.script` that checks the version and adds a dep of merl in the case it is <18.

**Comment by ricecake** [comment]
That's fair.  I'll see if I can get that poked into place tonight.

**Comment by tsloughter** [comment]
I just took care of it. Let me know if it works as you'd expect.

**Comment by ricecake** [comment]
Yup, looks like that does it.  Thanks much!

**Pull request closed without merging**
